my_variable="Pomodoro está barato"
print(my_variable)

print(len(my_variable))

my_into_to_str_variable="No me gustan las tempuras"
print(my_into_to_str_variable)

print(my_into_to_str_variable)

my_bool_variable=False
print("Este es el valor de:", my_bool_variable,my_variable,my_into_to_str_variable)
#Operadores

print(5 != 7 )
print(3 < 4 )
print(4 == 4)
print(3>=4)

print(3!=4)

print("Hola" > "HOLA")
print("HOLA" == "HOLA")
print("HOLA" > "hola")

#Operadores lógicos

print(3 >= 3)
print(not(3 > 3))
print(3 < 3)
print(not(3 < 3))

##03STRINGS
"FORMATEAR STRINGS"

name,surname,age="Antonio","Martinez",54
print("Mi nombre es {} {} y mi edad es {}".format(name,surname,age) )

name, surname, age = "Anthony", "Martinez", 25
print("Mi nombre es {} {} y mi edad es {}".format(name,surname,age))
"la forma menos optima,menos recomendada y mas complicada seria asi:"
print("Mi nombre es " + name + " " + surname + " y mi edad es " + str(age))
"usamos un str para concatenar la variable (age) que tiene un valor de numerico y se necesita hacer la transformación para que funcione"

##REPASO DEL APARTADO 03 STRINGS 

name,surname,age="Olga","Campoverde",48
print("Mi nombre es {} {} y mi edad es {}".format(name,surname,age))

#11/03/2023

n1,n2,n3=1,4,15
suma=n1 + n2 + n3
multiplicacion=n1 * n2
multiplicacion2=n1 * n3
print(suma)
print(multiplicacion)
print(multiplicacion2)

print(3/2)
print(3**2)
print(10*15)

my_variable="My string variable"
print(my_variable)

 my_list="Hola bro"
 print(my_list)
